name: compile

on:
  push:
    branches: [core]
    paths: ["**.zig", "**.dt", "src/inspiration", ".github/workflows/*.yml"]

  pull_request:
    branches: [core]
    paths: ["**.zig", "**.dt", "src/inspiration", ".github/workflows/*.yml"]

jobs:
  compile:

    strategy:
      matrix:
        zig_version: [0.14.0, 0.13.0, 0.12.0, 0.11.0]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: futz with build.zig.zon (name)
        if: matrix.zig_version != '0.14.0'
        run: |
          sed -i 's/\.dt/"dt"/' build.zig.zon

      - name: zig build
        run: |
          zig env
          zig build

      - name: zig build test
        run: |
          zig env
          zig build test

      - name: zig build cross
        run: |
          zig env
          zig build cross
